CREATE TABLE IF NOT EXISTS prediction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    crop_name VARCHAR(50) NOT NULL,
    disease_name VARCHAR(100) NOT NULL,
    raw_class VARCHAR(100) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    severity VARCHAR(20) NOT NULL,
    model_version VARCHAR(50) NOT NULL,
    advisory VARCHAR(1000) NOT NULL,
    top_predictions VARCHAR(2000),
    timestamp TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prediction_timestamp ON prediction_history (timestamp);
CREATE INDEX IF NOT EXISTS idx_prediction_session ON prediction_history (session_id);
