export function printDiagnosisReport(result) {
  const html = `<!DOCTYPE html>
<html><head><title>KrishiCare Report</title>
<style>
  body { font-family: Arial, sans-serif; padding: 32px; color: #222; }
  h1 { color: #16a34a; margin-bottom: 4px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  .section { margin-bottom: 20px; }
  .label { font-weight: bold; color: #444; }
  .bar { background: #e5e7eb; height: 8px; border-radius: 4px; margin-top: 4px; }
  .fill { background: #16a34a; height: 8px; border-radius: 4px; }
</style></head><body>
  <h1>KrishiCare Diagnosis</h1>
  <p class="meta">${new Date(result.timestamp || Date.now()).toLocaleString()}</p>
  <div class="section"><span class="label">Crop:</span> ${result.cropName}</div>
  <div class="section"><span class="label">Diagnosis:</span> ${result.diseaseName}</div>
  <div class="section"><span class="label">Confidence:</span> ${result.confidence?.toFixed(1)}%</div>
  <div class="section"><span class="label">Severity:</span> ${result.severity || 'N/A'}</div>
  <div class="section"><span class="label">Model:</span> ${result.modelVersion || 'N/A'}</div>
  <div class="section"><span class="label">Advisory:</span><br/>${result.advisory}</div>
  ${
    result.topPredictions?.length
      ? `<div class="section"><span class="label">Top predictions:</span><ul>${result.topPredictions
          .map((p) => `<li>${p.diseaseName} — ${p.confidence?.toFixed(1)}%</li>`)
          .join('')}</ul></div>`
      : ''
  }
  <p style="margin-top:40px;font-size:12px;color:#999">Generated by KrishiCare AI — not a substitute for professional agronomy advice.</p>
</body></html>`

  const win = window.open('', '_blank')
  win.document.write(html)
  win.document.close()
  win.focus()
  win.print()
}
